### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by risotoonero** [fe1ixxu/ALMA#66]
OK,Now I have a new problem. I first used a GPU with 24GB memory to fine-tune LLaMA-2-7B on monolingual OSCAR data (stage 1), and then it gave an error: `torch.cuda.OutOfMemoryError: CUDA out of memory`. It needs a little more than 24GB of memory. I thought it was because of insufficient memory. Later I tried a GPU with 48GB memory, and it still gave an error `torch.cuda.OutOfMemoryError: CUDA out of memory`. I don't think this is not enough to fine-tune LLaMA-2-7B,and I want to know what is wrong. Can you help me? Thank you very much

mono_ft.sh

```
OUTPUT_DIR=${1:-"./llama-2-7b-oscar-ft"}
export HF_DATASETS_CACHE="/root/.cache/huggingface_cache/datasets"
export TRANSFORMERS_CACHE="/root/.cache/models/"

port=$(( RANDOM % (50000 - 30000 + 1 ) + 30000 ))
accelerate launch --main_process_port ${port} --config_file /root/data/experiments/ALMA-master/configs/deepspeed_train_config.yaml \
    run_llmmt.py \
    --model_name_or_path /root/data/hf_hub/Llama-2-7b-hf \
    --oscar_data_path /root/oscar \
    --oscar_data_lang zh,ja \
    --interleave_probs "0.5,0.5" \
    --streaming \
    --max_steps 8000 \
    --do_train \
    --fp16 \
    --low_cpu_mem_usage \
    --learning_rate 2e-5 \
    --weight_decay 0.01 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --warmup_ratio 0.01 \
    --ignore_pad_token_for_loss \
    --ignore_prompt_token_for_loss \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --save_strategy steps \
    --save_steps 1000 \
    --save_total_limit 1 \
    --logging_strategy steps \
    --logging_steps 1 \
    --output_dir ${OUTPUT_DIR} \
    --max_new_tokens 256 \
    --max_source_length 256 \
    --seed 42 \
    --overwrite_output_dir \
    --report_to none
```

deepspeed_train_config.yaml

```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 4
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: cpu
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

![1730282064252](https://github.com/user-attachments/assets/739d17a3-ba86-487f-991a-84a41aec8053)
![1730282083318](https://github.com/user-attachments/assets/7cfb8201-9132-418b-a754-1e0bcc60e312)
![1730282177322](https://github.com/user-attachments/assets/491902d2-604e-4668-bf33-17a5f49ce221)
